// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbLvD6r5wNzhkyjrrfHm5Gl5kMno1LZmc',
    appId: '1:713081952345:web:08e9755eaf219785e8f948',
    messagingSenderId: '713081952345',
    projectId: 'is-devops-prugsajika',
    authDomain: 'is-devops-prugsajika.firebaseapp.com',
    storageBucket: 'is-devops-prugsajika.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSg-Y67uFiGy1fC7fLb4HSLJptASjkIzk',
    appId: '1:713081952345:android:2cd52a7bfa659499e8f948',
    messagingSenderId: '713081952345',
    projectId: 'is-devops-prugsajika',
    storageBucket: 'is-devops-prugsajika.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwYvbU-wlov_FdCC2DGw6CKCSuhJ0bws',
    appId: '1:713081952345:ios:316181600ee3810de8f948',
    messagingSenderId: '713081952345',
    projectId: 'is-devops-prugsajika',
    storageBucket: 'is-devops-prugsajika.appspot.com',
    iosClientId: '713081952345-uu0v70s3r3vr6tbmgcj5n7d0fsgr4a3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.grubngoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwYvbU-wlov_FdCC2DGw6CKCSuhJ0bws',
    appId: '1:713081952345:ios:316181600ee3810de8f948',
    messagingSenderId: '713081952345',
    projectId: 'is-devops-prugsajika',
    storageBucket: 'is-devops-prugsajika.appspot.com',
    iosClientId: '713081952345-uu0v70s3r3vr6tbmgcj5n7d0fsgr4a3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.grubngoApp',
  );
}
